# Generated by Django 3.2.25 on 2025-08-13 03:27

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0011_alter_paymentplan_interval"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionAddon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Description"
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Stripe Price ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe Product ID"
                    ),
                ),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("additional_member", "Additional Member"),
                            ("storage_upgrade", "Storage Upgrade"),
                            ("priority_support", "Priority Support"),
                            ("equipment_rental", "Equipment Rental"),
                            ("custom", "Custom Add-on"),
                        ],
                        max_length=50,
                        verbose_name="Add-on Type",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Is this add-on visible to members?"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="aud", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("cost", models.IntegerField(verbose_name="Cost in cents")),
                (
                    "interval_count",
                    models.IntegerField(
                        default=1, verbose_name="Billing interval count"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("Month", "month"), ("Week", "week"), ("Day", "day")],
                        default="month",
                        max_length=10,
                        verbose_name="Billing interval",
                    ),
                ),
                (
                    "max_quantity",
                    models.IntegerField(
                        default=10, verbose_name="Maximum quantity allowed"
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=1, verbose_name="Minimum quantity required"
                    ),
                ),
                (
                    "stripe_synced",
                    models.BooleanField(
                        default=False, verbose_name="Synced with Stripe"
                    ),
                ),
                (
                    "last_stripe_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Stripe Sync"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Add-on",
                "verbose_name_plural": "Subscription Add-ons",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "subscription-addon"
                ),
                models.Model,
            ),
        ),
    ]
