# Generated by Django 3.2.25 on 2025-08-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0013_auto_20250813_1354"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscriptionaddon",
            unique_together={("name", "addon_type")},
        ),
    ]
