# Generated by Django 3.2.25 on 2026-01-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0014_add_unique_constraint_to_subscription_addon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionaddon",
            name="addon_type",
            field=models.CharField(
                choices=[
                    ("additional_member", "Additional Member"),
                    ("storage_upgrade", "Storage Upgrade"),
                    ("priority_support", "Priority Support"),
                    ("equipment_rental", "Equipment Rental"),
                    ("shelf_rental", "Shelf Rental"),
                    ("custom", "Custom Add-on"),
                ],
                max_length=50,
                verbose_name="Add-on Type",
            ),
        ),
    ]
