x-mm-env: &mm-env
  MM_ENV: Production
  MM_SECRET_KEY: ${MM_SECRET_KEY:?Set MM_SECRET_KEY in docker/.env}
  MM_USE_POSTGRES: "true"
  MM_REDIS_HOST: redis://mm-redis:6379/0
  POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in docker/.env}
  POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in docker/.env}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in docker/.env}
  POSTGRES_HOST: mm-postgres

services:
  mm-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in docker/.env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in docker/.env}
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in docker/.env}
    volumes:
      - mm-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MemberMatters Redis
  mm-redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MemberMatters
  mm-webapp:
    image: rocmakers/membermatters
    restart: always
    environment:
      <<: *mm-env
    ports:
      - "8000:8000"
    depends_on:
      mm-postgres:
        condition: service_healthy
      mm-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 15

  # MemberMatters Celery Worker
  mm-celery-worker:
    image: rocmakers/membermatters
    restart: always
    environment:
      <<: *mm-env
      MM_RUN_MODE: celery_worker
    depends_on:
      mm-webapp:
        condition: service_healthy
      mm-redis:
        condition: service_healthy

  # MemberMatters Celery Beat
  mm-celery-beat:
    image: rocmakers/membermatters
    restart: always
    environment:
      <<: *mm-env
      MM_RUN_MODE: celery_beat
    depends_on:
      mm-webapp:
        condition: service_healthy
      mm-celery-worker:
        condition: service_started
      mm-redis:
        condition: service_healthy

volumes:
  mm-postgres-volume:
    driver: local
