services:
  mm-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=membermatters
      - POSTGRES_PASSWORD=membermatters
      - POSTGRES_DB=membermatters
    volumes:
      - mm-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U membermatters"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MemberMatters Redis
  mm-redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MemberMatters
  mm-webapp:
    image: rocmakers/membermatters
    restart: always
    environment:
      MM_ENV: "Production"
      MM_SECRET_KEY: "CHANGE_ME"
      MM_USE_POSTGRES: True
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      mm-postgres:
        condition: service_healthy
      mm-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 15

  # MemberMatters Celery Worker
  mm-celery-worker:
    image: rocmakers/membermatters
    restart: always
    environment:
      MM_ENV: "Production"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_worker"
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    depends_on:
      mm-webapp:
        condition: service_healthy
      mm-redis:
        condition: service_healthy

  # MemberMatters Celery Beat
  mm-celery-beat:
    image: rocmakers/membermatters
    restart: always
    environment:
      MM_ENV: "Production"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_beat"
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    depends_on:
      mm-webapp:
        condition: service_healthy
      mm-celery-worker:
        condition: service_started
      mm-redis:
        condition: service_healthy

volumes:
  mm-postgres-volume:
    driver: local
