# Generated by Django 3.2.25 on 2026-04-24 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0012_subscriptionaddon"),
        ("profile", "0018_alter_profile_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("billing-group"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pending_billing_group_invite_token",
            field=models.UUIDField(
                blank=True,
                help_text="Temporarily stores invitation token during registration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="billing_group_invite",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="billing_group_member",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BillingGroupInvite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                (
                    "invitation_token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("expires_date", models.DateTimeField()),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_date", models.DateTimeField(blank=True, null=True)),
                ("invalidated", models.BooleanField(default=False)),
                ("invalidated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="profile.billinggroup",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_billing_group_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "billing-group-invite"
                ),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="billinggroup",
            name="primary_member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_group_primary_member",
                to="profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="billing_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="profile.billinggroup",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="billing_group_invite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_invites",
                to="profile.billinggroup",
            ),
        ),
        migrations.CreateModel(
            name="BillingGroupMemberAddon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("locked_cost", models.IntegerField()),
                ("locked_currency", models.CharField(default="aud", max_length=3)),
                ("locked_interval", models.CharField(max_length=10)),
                ("locked_interval_count", models.IntegerField(default=1)),
                ("date_locked", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_subscription_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_group_members",
                        to="api_admin_tools.subscriptionaddon",
                    ),
                ),
                (
                    "billing_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_addons",
                        to="profile.billinggroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_group_addons",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("billing_group", "member", "addon")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "billing-group-member-addon"
                ),
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="billinggroupinvite",
            index=models.Index(
                fields=["email", "billing_group"], name="profile_bil_email_848a39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billinggroupinvite",
            index=models.Index(
                fields=["expires_date"], name="profile_bil_expires_1ff736_idx"
            ),
        ),
    ]
