# Generated by Django 3.2.25 on 2026-04-24 02:34

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0012_subscriptionaddon"),
        ("profile", "0019_billing_group_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_requests",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("shelf-request"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("cancelled", "Cancelled - Next Occupant Assigned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("next_available_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_shelves",
                        to="profile.profile",
                    ),
                ),
                (
                    "next_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_shelves",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("shelf"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MemberShelfAddon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("locked_cost", models.IntegerField()),
                ("locked_currency", models.CharField(default="aud", max_length=3)),
                ("locked_interval", models.CharField(max_length=10)),
                ("locked_interval_count", models.IntegerField(default=1)),
                ("date_locked", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_subscription_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_rentals",
                        to="api_admin_tools.subscriptionaddon",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_addons",
                        to="profile.profile",
                    ),
                ),
                (
                    "shelf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon",
                        to="profile.shelf",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "member-shelf-addon"
                ),
                models.Model,
            ),
        ),
    ]
