# Generated by Django 3.2.25 on 2025-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0023_rename_collective_to_billing_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collective_invite',
            new_name='billing_group_invite',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='collective_member',
            new_name='billing_group_member',
        ),
    ] 