# Generated by Django on 2025-08-29 for billing group member addon pricing
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0023_rename_collective_to_billing_group"),
        ("api_admin_tools", "0012_subscriptionaddon"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingGroupMemberAddon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "locked_cost",
                    models.IntegerField(
                        help_text="Cost in cents when this member was added to the billing group"
                    ),
                ),
                ("locked_currency", models.CharField(default="aud", max_length=3)),
                ("locked_interval", models.CharField(max_length=10)),
                ("locked_interval_count", models.IntegerField(default=1)),
                ("date_locked", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_addons",
                        to="profile.billinggroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_group_addons",
                        to="profile.profile",
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_group_members",
                        to="api_admin_tools.subscriptionaddon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Group Member Add-on",
                "verbose_name_plural": "Billing Group Member Add-ons",
                "unique_together": [["billing_group", "member", "addon"]],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "billing_group_member_addon"
                ),
                models.Model,
            ),
        ),
    ]
