# Generated by Django 3.2.25 on 2025-08-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0024_billing_group_member_addon_pricing"),
        ("profile", "0024_update_user_billing_group_fields"),
    ]

    operations = []
