# Generated by Django 3.2.25 on 2025-09-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0025_merge_20250829_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinggroupmemberaddon",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe price ID created for this member's locked pricing",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billinggroupmemberaddon",
            name="stripe_subscription_item_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe subscription item ID for this member's addon",
                max_length=255,
                null=True,
            ),
        ),
    ]
