# Generated by Django 3.2.25 on 2025-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0026_auto_20250905_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("active", "Active"),
                    ("cancelling", "Cancelling"),
                    ("group_active", "Group Member (Active)"),
                    ("group_inactive", "Group Member (Inactive)"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
