# Generated by Django 3.2.25 on 2025-09-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0027_add_group_subscription_states"),
    ]

    operations = []
