# Generated by Django 3.2.25 on 2025-12-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0029_fix_billing_group_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingGroupInvite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the invited person (stored in lowercase)",
                        max_length=255,
                    ),
                ),
                (
                    "invitation_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token embedded in the registration URL",
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_date",
                    models.DateTimeField(
                        help_text="When this invitation expires (default 7 days)"
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False, help_text="Whether the invitation was accepted"
                    ),
                ),
                (
                    "accepted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "invalidated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this invitation was invalidated (e.g., by sending a new one)",
                    ),
                ),
                (
                    "invalidated_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was invalidated",
                        null=True,
                    ),
                ),
                (
                    "billing_group",
                    models.ForeignKey(
                        help_text="The billing group they're being invited to join",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="profile.billinggroup",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="The user who sent this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_billing_group_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Group Invitation",
                "verbose_name_plural": "Billing Group Invitations",
                "ordering": ["-created_date"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "billing_group_invite"
                ),
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="billinggroupinvite",
            index=models.Index(
                fields=["email", "billing_group"], name="profile_bil_email_848a39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billinggroupinvite",
            index=models.Index(
                fields=["expires_date"], name="profile_bil_expires_1ff736_idx"
            ),
        ),
    ]
