# Generated by Django 3.2.25 on 2025-12-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0030_auto_20251203_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pending_billing_group_invite_token",
            field=models.UUIDField(
                blank=True,
                help_text="Temporarily stores invitation token during registration process",
                null=True,
            ),
        ),
    ]
