# Generated by Django 3.2.25 on 2026-01-23 01:19

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0015_add_shelf_rental_models"),
        ("profile", "0031_profile_pending_billing_group_invite_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelfRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Number of shelves requested"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member requesting a shelf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_requests",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shelf Request",
                "verbose_name_plural": "Shelf Requests",
                "ordering": ["requested_at"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("shelf_request"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        help_text="Shelf identifier/number", max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("cancelled", "Cancelled - Next Occupant Assigned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when current member started renting",
                        null=True,
                    ),
                ),
                (
                    "next_available_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when shelf becomes available for next occupant",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current member renting this shelf",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_shelves",
                        to="profile.profile",
                    ),
                ),
                (
                    "next_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next member to occupy this shelf (when current rental is cancelled)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_shelves",
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shelf",
                "verbose_name_plural": "Shelves",
                "ordering": ["number"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("shelf"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MemberShelfAddon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "locked_cost",
                    models.IntegerField(
                        help_text="Cost in cents when this shelf was assigned"
                    ),
                ),
                ("locked_currency", models.CharField(default="aud", max_length=3)),
                ("locked_interval", models.CharField(max_length=10)),
                ("locked_interval_count", models.IntegerField(default=1)),
                ("date_locked", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_subscription_item_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription item ID for this shelf rental",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe price ID created for this member's locked pricing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        help_text="The subscription addon for shelf rental",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_rentals",
                        to="api_admin_tools.subscriptionaddon",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member renting the shelf",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_addons",
                        to="profile.profile",
                    ),
                ),
                (
                    "shelf",
                    models.OneToOneField(
                        help_text="The shelf being rented",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon",
                        to="profile.shelf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Shelf Add-on",
                "verbose_name_plural": "Member Shelf Add-ons",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "member_shelf_addon"
                ),
                models.Model,
            ),
        ),
    ]
